# Cloud Build configuration for Next.js frontend deployment to Cloud Run
steps:
  # Step 1: Build the Docker image for AMD64/Linux platform
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform', 'linux/amd64',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/document-intelligence/frontend:$BUILD_ID',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/document-intelligence/frontend:latest',
      '.'
    ]
    id: 'build-image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/document-intelligence/frontend:latest']
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'document-intelligence-ui-dev'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/document-intelligence/frontend:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--concurrency=80'
      # Simplified 2-URL configuration
      - '--set-env-vars=NEXT_PUBLIC_API_URL=https://document-intelligence-api-dev-tfibpeg5zq-uc.a.run.app'
      - '--set-env-vars=NEXT_PUBLIC_AI_API_URL=https://document-intelligence-ai-api-dev-tfibpeg5zq-uc.a.run.app'
      - '--set-env-vars=NEXT_PUBLIC_APP_NAME=Biz-To-Bricks'
      - '--set-env-vars=NEXT_PUBLIC_APP_VERSION=1.0.0'
      - '--set-env-vars=NEXT_PUBLIC_AUTH_ENABLED=true'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=NEXT_TELEMETRY_DISABLED=1'
      - '--set-env-vars=HOSTNAME=0.0.0.0'
    id: 'deploy-to-cloudrun'
    waitFor: ['push-image']

# Configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'

# Images to push to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/document-intelligence/frontend:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/document-intelligence/frontend:latest'
